const PERMISSIONS = {
  ORG_UPDATE: 'ORG_UPDATE',
  MEMBER_INVITE: 'MEMBER_INVITE',
  MEMBER_MANAGE: 'MEMBER_MANAGE',
  PAYMENT_CREATE: 'PAYMENT_CREATE',
  COMPANY_READ: 'COMPANY_READ',
  COMPANY_LINK: 'COMPANY_LINK',
  LEDGER_READ: 'LEDGER_READ',
  CUSTOMER_READ: 'CUSTOMER_READ',
  SUPPLIER_READ: 'SUPPLIER_READ',
  STOCK_READ: 'STOCK_READ',
  VOUCHER_READ: 'VOUCHER_READ',
  REPORTS_READ: 'REPORTS_READ',
  COMMAND_CREATE: 'COMMAND_CREATE',
  CONNECTOR_STATUS: 'CONNECTOR_STATUS',
  SYNC_MASTER: 'SYNC_MASTER',
  SYNC_LEDGER: 'SYNC_LEDGER',
  SYNC_VOUCHER: 'SYNC_VOUCHER',
  SYNC_STOCK: 'SYNC_STOCK',
};

const ALL_PERMISSIONS = Object.values(PERMISSIONS);

const ROLE = {
  OWNER: 'OWNER',
  ADMIN: 'ADMIN',
  ACCOUNTANT: 'ACCOUNTANT',
  VIEWER: 'VIEWER',
};

const ROLE_PERMISSIONS = {
  [ROLE.OWNER]: ALL_PERMISSIONS,
  [ROLE.ADMIN]: [
    PERMISSIONS.ORG_UPDATE,
    PERMISSIONS.MEMBER_INVITE,
    PERMISSIONS.MEMBER_MANAGE,
    PERMISSIONS.COMPANY_READ,
    PERMISSIONS.LEDGER_READ,
    PERMISSIONS.CUSTOMER_READ,
    PERMISSIONS.SUPPLIER_READ,
    PERMISSIONS.STOCK_READ,
    PERMISSIONS.VOUCHER_READ,
    PERMISSIONS.REPORTS_READ,
    PERMISSIONS.COMMAND_CREATE,
    PERMISSIONS.CONNECTOR_STATUS,
  ],
  [ROLE.ACCOUNTANT]: [
    PERMISSIONS.COMPANY_READ,
    PERMISSIONS.LEDGER_READ,
    PERMISSIONS.CUSTOMER_READ,
    PERMISSIONS.SUPPLIER_READ,
    PERMISSIONS.STOCK_READ,
    PERMISSIONS.VOUCHER_READ,
    PERMISSIONS.REPORTS_READ,
    PERMISSIONS.COMMAND_CREATE,
    PERMISSIONS.CONNECTOR_STATUS,
  ],
  [ROLE.VIEWER]: [
    PERMISSIONS.COMPANY_READ,
    PERMISSIONS.LEDGER_READ,
    PERMISSIONS.CUSTOMER_READ,
    PERMISSIONS.SUPPLIER_READ,
    PERMISSIONS.STOCK_READ,
    PERMISSIONS.VOUCHER_READ,
    PERMISSIONS.REPORTS_READ,
    PERMISSIONS.CONNECTOR_STATUS,
  ],
};

const ERROR_CODES = {
  SUBSCRIPTION_EXPIRED: 'SUBSCRIPTION_EXPIRED',
  SUBSCRIPTION_REQUIRED: 'SUBSCRIPTION_REQUIRED',
  AUTH_REVOKED: 'AUTH_REVOKED',
  TALLY_LINK_REQUIRED: 'TALLY_LINK_REQUIRED',
  OTP_INVALID: 'OTP_INVALID',
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_MAX_ATTEMPTS: 'OTP_MAX_ATTEMPTS',
  OTP_COOLDOWN: 'OTP_COOLDOWN',
  FORBIDDEN: 'FORBIDDEN',
  UNAUTHORIZED: 'UNAUTHORIZED',
  SEAT_LIMIT_REACHED: 'SEAT_LIMIT_REACHED',
  PLAN_NOT_FOUND: 'PLAN_NOT_FOUND',
  PAYMENT_VERIFICATION_FAILED: 'PAYMENT_VERIFICATION_FAILED',
  INVALID_SIGNATURE: 'INVALID_SIGNATURE',
  CONNECTOR_NOT_FOUND: 'CONNECTOR_NOT_FOUND',
  COMMAND_NOT_FOUND: 'COMMAND_NOT_FOUND',
  SYNC_JOB_NOT_FOUND: 'SYNC_JOB_NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
};

module.exports = {
  PERMISSIONS,
  ALL_PERMISSIONS,
  ROLE,
  ROLE_PERMISSIONS,
  ERROR_CODES,
};
