const PERMISSIONS = {
  ORG_UPDATE: "ORG_UPDATE",
  MEMBER_INVITE: "MEMBER_INVITE",
  MEMBER_MANAGE: "MEMBER_MANAGE",
  PAYMENT_CREATE: "PAYMENT_CREATE",
  COMPANY_READ: "COMPANY_READ",
  COMPANY_LINK: "COMPANY_LINK",
  LEDGER_READ: "LEDGER_READ",
  CUSTOMER_READ: "CUSTOMER_READ",
  SUPPLIER_READ: "SUPPLIER_READ",
  STOCK_READ: "STOCK_READ",
  VOUCHER_READ: "VOUCHER_READ",
  REPORTS_READ: "REPORTS_READ",
  COMMAND_CREATE: "COMMAND_CREATE",
  CONNECTOR_STATUS: "CONNECTOR_STATUS",
  SYNC_MASTER: "SYNC_MASTER",
  SYNC_LEDGER: "SYNC_LEDGER",
  SYNC_VOUCHER: "SYNC_VOUCHER",
  SYNC_STOCK: "SYNC_STOCK",
  EWAY_BILL_GENERATE: "EWAY_BILL_GENERATE",
  GSP_SETTINGS_MANAGE: "GSP_SETTINGS_MANAGE",
};

const MODULE_KEYS = [
  "dashboard",
  "create-voucher",
  "sales",
  "purchase",
  "cash-bank",
  "collect-payments",
  "parties",
  "items",
  "reports",
  "my-entries",
  "vouchers",
  "my-ledgers",
  "gst-search",
  "my-eway-bill",
  "data-backup",
];

const MODULE_SUBMODULES = {
  "create-voucher": [
    "/create-voucher/Quotation",
    "/create-voucher/SalesInvoice",
    "/create-voucher/Receipt",
    "/create-voucher/Payment",
    "/create-voucher/SalesOrder",
    "/create-voucher/PurchaseInvoice",
    "/create-voucher/Journal",
    "/create-voucher/Contra",
    "/create-voucher/PurchaseOrder",
    "/create-voucher/CreditNote",
    "/create-voucher/DebitNote",
    "/create-voucher/StockJournal",
    "/create-voucher/PhysicalStock",
    "/create-voucher/ReceiptNote",
    "/create-voucher/DeliveryNote",
  ],
  sales: [
    "/sales",
    "/creditNote",
    "/receipt",
    "/receivables",
    "/salesorder",
    "/deliveryNote",
  ],
  purchase: [
    "/purchase",
    "/debitNote",
    "/payments",
    "/payables",
    "/purchaseorder",
    "/receiptNote",
  ],
  "cash-bank": ["/cash-bank/cash", "/cash-bank/bank"],
  reports: [
    "/trial-balance",
    "/day-book",
    "/profit-loss",
    "/balance-sheet",
    "/voucher-lines",
  ],
  "my-entries": [
    "/my-vouchers",
    "/my-quotations",
    "/my-receipts",
    "/my-payments",
    "/my-sales-order",
    "/my-purchase",
    "/my-journal",
    "/my-contra",
    "/my-purchase-order",
    "/my-credit-note",
    "/my-debit-note",
    "/my-stock-journal",
    "/my-physical-stock",
    "/my-receipt-note",
    "/my-delivery-note",
    "/my-invoices",
    "/my-parties",
    "/my-stock-items",
  ],
};

const ALL_ALLOWED_MODULE_KEYS = [
  ...MODULE_KEYS,
  ...Object.values(MODULE_SUBMODULES).flat(),
];

const ALL_PERMISSIONS = Object.values(PERMISSIONS);

const ROLE = {
  OWNER: "OWNER",
  ADMIN: "ADMIN",
  ACCOUNTANT: "ACCOUNTANT",
  VIEWER: "VIEWER",
};

const ROLE_PERMISSIONS = {
  [ROLE.OWNER]: ALL_PERMISSIONS,
  [ROLE.ADMIN]: [
    PERMISSIONS.ORG_UPDATE,
    PERMISSIONS.MEMBER_INVITE,
    PERMISSIONS.MEMBER_MANAGE,
    PERMISSIONS.COMPANY_READ,
    PERMISSIONS.LEDGER_READ,
    PERMISSIONS.CUSTOMER_READ,
    PERMISSIONS.SUPPLIER_READ,
    PERMISSIONS.STOCK_READ,
    PERMISSIONS.VOUCHER_READ,
    PERMISSIONS.REPORTS_READ,
    PERMISSIONS.COMMAND_CREATE,
    PERMISSIONS.CONNECTOR_STATUS,
    PERMISSIONS.EWAY_BILL_GENERATE,
    PERMISSIONS.GSP_SETTINGS_MANAGE,
  ],
  [ROLE.ACCOUNTANT]: [
    PERMISSIONS.COMPANY_READ,
    PERMISSIONS.LEDGER_READ,
    PERMISSIONS.CUSTOMER_READ,
    PERMISSIONS.SUPPLIER_READ,
    PERMISSIONS.STOCK_READ,
    PERMISSIONS.VOUCHER_READ,
    PERMISSIONS.REPORTS_READ,
    PERMISSIONS.COMMAND_CREATE,
    PERMISSIONS.CONNECTOR_STATUS,
    PERMISSIONS.EWAY_BILL_GENERATE,
    PERMISSIONS.GSP_SETTINGS_MANAGE,
  ],
  [ROLE.VIEWER]: [
    PERMISSIONS.COMPANY_READ,
    PERMISSIONS.LEDGER_READ,
    PERMISSIONS.CUSTOMER_READ,
    PERMISSIONS.SUPPLIER_READ,
    PERMISSIONS.STOCK_READ,
    PERMISSIONS.VOUCHER_READ,
    PERMISSIONS.REPORTS_READ,
    PERMISSIONS.CONNECTOR_STATUS,
  ],
};

const ERROR_CODES = {
  SUBSCRIPTION_EXPIRED: "SUBSCRIPTION_EXPIRED",
  SUBSCRIPTION_REQUIRED: "SUBSCRIPTION_REQUIRED",
  AUTH_REVOKED: "AUTH_REVOKED",
  TALLY_LINK_REQUIRED: "TALLY_LINK_REQUIRED",
  OTP_INVALID: "OTP_INVALID",
  OTP_EXPIRED: "OTP_EXPIRED",
  OTP_MAX_ATTEMPTS: "OTP_MAX_ATTEMPTS",
  OTP_COOLDOWN: "OTP_COOLDOWN",
  FORBIDDEN: "FORBIDDEN",
  UNAUTHORIZED: "UNAUTHORIZED",
  SEAT_LIMIT_REACHED: "SEAT_LIMIT_REACHED",
  PLAN_NOT_FOUND: "PLAN_NOT_FOUND",
  PAYMENT_VERIFICATION_FAILED: "PAYMENT_VERIFICATION_FAILED",
  INVALID_SIGNATURE: "INVALID_SIGNATURE",
  CONNECTOR_NOT_FOUND: "CONNECTOR_NOT_FOUND",
  COMMAND_NOT_FOUND: "COMMAND_NOT_FOUND",
  SYNC_JOB_NOT_FOUND: "SYNC_JOB_NOT_FOUND",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",
  EMAIL_SEND_FAILED: "EMAIL_SEND_FAILED",
  GSP_AUTH_FAILED: "GSP_AUTH_FAILED",
  EWAY_BILL_GENERATION_FAILED: "EWAY_BILL_GENERATION_FAILED",
  EWAY_BILL_CANCEL_FAILED: "EWAY_BILL_CANCEL_FAILED",
  GSP_CREDENTIALS_NOT_CONFIGURED: "GSP_CREDENTIALS_NOT_CONFIGURED",
  ACCOUNT_SUSPENDED: "ACCOUNT_SUSPENDED",
  OUTSIDE_LOGIN_SCHEDULE: "OUTSIDE_LOGIN_SCHEDULE",
};

module.exports = {
  PERMISSIONS,
  MODULE_KEYS,
  MODULE_SUBMODULES,
  ALL_ALLOWED_MODULE_KEYS,
  ALL_PERMISSIONS,
  ROLE,
  ROLE_PERMISSIONS,
  ERROR_CODES,
};
